### ISSUE TITLE
Run gpg with --disable-dirmngr

### ISSUE THREAD

**Issue by matoro** [projg2/getuto#5]
Trying to add this to my chroot scripts, and it leaves a `dirmngr` process running as root, preventing unmounts.  This can be prevented entirely by adding `--disable-dirmngr` argument, or including `gpgconf --kill dirmngr` (just like what is done right now with `gpg-agent`).

**Comment by damiandudycz** [comment]
Im having similar issue. Is there some way to run getuto without leaving process dirmngr running?
